### ISSUE TITLE
Mitochondria workflow

### ISSUE THREAD

**Issue by Gwennid** [nf-core/raredisease#48]
We have agreed to use the mitochondria workflow currently implemented at [GATK best practices](https://gatk.broadinstitute.org/hc/en-us/articles/4403870837275-Mitochondrial-short-variant-discovery-SNVs-Indels-).

The following steps are included. Modules already exist for some of them; all modules need to be included in a subworkflow. We plan to have the mitochondrial subworkflow run by default, but to have the possibility to turn it off and also to turn off the calling of variants for the autosomes.

- [x] Samtools subsampling [nf-core/raredisease] #49
- [x] RevertSam [nf-core/raredisease]#106
- [x] SamtoFastq [nf-core/raredisease]#107
- [x] BWA
- [x] GATK MergeBamAlignment
- [x] Picard MarkDuplicates 
- [x] Haplocheck  [nf-core/raredisease]#111
- [x] call variants with GATK [Mutect2](https://bioconda.github.io/recipes/gatk4/README.html)
- [x] Picard LiftoverVCF
- [x] GATK Mergevcfs  [nf-core/raredisease]#113
- [x] GATK4 [FilterMutectCalls]   [nf-core/raredisease]#115 
- [ ] GATK Filterblacklist
- [x] annotation with HmtNote 
- [x] annotation with [vep](https://bioconda.github.io/recipes/bioconductor-ensemblvep/README.html). Because it requires a database, special care has to be taken to run it offline. Cf nf-core/sarek too.
- [ ] `bcftools query` and
- [ ] `bcftools view` to prepare input for haplogrep2
- [x] call mitochondrial haplogroup with haplogrep2  (To be included in workflow)
- [x] detect mitochondrial deletions with eKLIPse (not in bioconda) (To be included in workflow) (to be checked )

This list can be modified as new issues are created and new modules are added.

Test dataset including mtDNA: https://github.com/nf-core/test-datasets/tree/raredisease

**Comment by Gwennid** [comment]
@sysbiocoder , @Lucpen and @Gwennid have discussed how to structure the mitochondria subworkflow. At the moment we are thinking of separating it in three: one part for each of the two parallel "tracks" (see [here](https://docs.google.com/drawings/d/1QZsgxM4zuArI-N2kuWzwJB5PpjwOu8XxJ3-DInlNYEk/edit)) and a main part with the three initial steps, that prepares the inputs for the two parallel tracks, calls them, and then joins the outputs and runs the end (annotation etc).

**Comment by ramprasadn** [comment]
Closing this issue since this feature is already implemented in the pipeline.
